trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: CmdLine@2
  inputs:
    script: 'jmeter -n -t "$(Pipeline.Workspace)\_jprajwalk_JmeterSamplePOC\AzurePipeline.jmx" -l "$(Pipeline.Workspace)\results.jtl"'
    workingDirectory: '$(Pipeline.Workspace)\_jprajwalk_JmeterSamplePOC\AzurePipeline.jmx'