trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Install JMeter
- script: |
    sudo apt-get update
    sudo apt-get install -y jmeter
  displayName: 'Install JMeter'

# Run JMeter command
- script: |
    jmeter -n -t "$(Pipeline.Workspace)/s/_jprajwalk_JmeterSamplePOC/AzurePipeline.jmx" -l "$(Pipeline.Workspace)/s/results.jtl"
    # Make sure to include the path to the results file
    mv "$(Pipeline.Workspace)/s/results.xml" "$(Pipeline.Workspace)/s/test-results/results.xml"
  displayName: 'Run JMeter Test'
  workingDirectory: '$(Pipeline.Workspace)'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Pipeline.Workspace)/s/test-results/results.xml'
    failTaskOnFailedTests: true