trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: 'jmeter -n -t "$(Pipeline.Workspace)\_jprajwalk_JmeterSamplePOC\AzurePipeline.jmx" -l "$(Pipeline.Workspace)\results.jtl"'
    workingDirectory: '$(Pipeline.Workspace)/s'